name: Trigger auto deployment for spring-app-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/spring-app-demo-AutoDeployTrigger-eeb33b87-9834-4745-aa98-16afd3cdda7f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPRINGAPPDEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPRINGAPPDEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPRINGAPPDEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.SPRINGAPPDEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPRINGAPPDEMO_REGISTRY_PASSWORD }}
          containerAppName: spring-app-demo
          resourceGroup: test
          imageToBuild: ghcr.io/spring-app-demo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


